### ISSUE TITLE
Uninitialized constant Pwa::Railtie::Mozaic

### ISSUE THREAD

**Issue by jonchay** [jonhue/pwa#1]
### Expected behavior
Mozaic class should be referencing mozaic gem.

### Actual behavior
Constant lookup causes Mozaic to be a child of `Railtie`.

### Steps to reproduce
1. Install `gem 'pwa'`
2. Run `rails s`
```
/Users/jonchay/.rvm/gems/ruby-2.4.3@taocampus/gems/pwa-3.0.0/lib/pwa/railtie.rb:7:in `block in <class:Railtie>': uninitialized constant Pwa::Railtie::Mozaic (NameError)
	from /Users/jonchay/.rvm/gems/ruby-2.4.3@taocampus/gems/railties-5.1.2/lib/rails/initializable.rb:30:in `instance_exec'
	from /Users/jonchay/.rvm/gems/ruby-2.4.3@taocampus/gems/railties-5.1.2/lib/rails/initializable.rb:30:in `run'
	from /Users/jonchay/.rvm/gems/ruby-2.4.3@taocampus/gems/railties-5.1.2/lib/rails/initializable.rb:59:in `block in run_initializers'
	from /Users/jonchay/.rvm/rubies/ruby-2.4.3/lib/ruby/2.4.0/tsort.rb:228:in `block in tsort_each'
```

### System configuration

**Ruby version**:
ruby 2.4.3p205 (2017-12-14 revision 61247) [x86_64-darwin17]

**Rails version**:
Rails 5.1.2

### Suggested Solution:
Add `require 'mozaic'` at the top of file under `lib/pwa/railtie.rb`:
```ruby
require 'rails/railtie'
require 'mozaic'

module Pwa
    class Railtie < Rails::Railtie

        initializer 'pwa.mozaic' do
            Mozaic.configure do |config|
                config.define_component 'pwa/manifest'
                config.define_component 'pwa/theme', default: '#FFFFFF'
            end
        end

    end
end
```

**Comment by jonhue** [comment]
Thank you for your help!
